appName: pdf-summarizer
environment: prod

containerPort: 8501

probes:
  path: /_stcore/health

replicaCount: 3

env:
  - name: OLLAMA_URL
    value: "http://ollama.platform.svc.cluster.local:11434"
  - name: OLLAMA_MODEL
    value: "llama3.2:1b"
